name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.26.6 # https://github.com/zephyrproject-rtos/docker-image
    strategy:
      matrix:
        app: [template]
        target: [esp32c3_devkitm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: workdir

      - name: Set variables
        working-directory: workdir
        id: vars
        run: |
            echo "{branch}={GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
            echo "{sha_short}=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Initialize
        working-directory: workdir
        run: |
          pip3 install -U west
          west update
          pip3 install -r deps/zephyr/scripts/requirements-base.txt

      - name: Build ${{ matrix.app }} for ${{ matrix.target }}
        working-directory: workdir
        run: |
          west build -b ${{ matrix.target }} -s apps/${{ matrix.app }} -p
          mkdir -p .out
          cp build/esp-idf/build/bootloader/bootloader.bin .out/${{ matrix.app }}_${{ matrix.target }}_bootloader.bin
          cp build/esp-idf/build/partition_singleapp.bin .out/${{ matrix.app }}_${{ matrix.target }}_partition_singleapp.bin
          cp build/zephyr/zephyr.bin .out/${{ matrix.app }}_${{ matrix.target }}_zephyr.bin

      - name: Archive firmware
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}_${{ matrix.app }}_${{ steps.vars.outputs.branch }}_${{ steps.vars.outputs.sha_short }}
          path: workdir/.out/
